console.log('hello world')
console.log('typeof document: ' + typeof document)
var app = document.createElement('div')
console.log('typeof window: ' + typeof window)
console.log('window === global: ' + (window === global))
console.log('typeof say: ' + typeof say)
console.log('typeof window.say: ' + typeof window.say)
console.log('typeof lib: ' + typeof lib)
console.log('typeof window.lib: ' + typeof window.lib)
console.log('typeof window.React: ' + typeof window.React)
console.log('typeof window.redom: ' + typeof window.redom)
console.log('typeof bestdog: ' + bestdog)
app.innerHTML = window.say('giraffe')
app.id = 'app'
console.log(window.say('to my little friend'))
document.body.appendChild(app)
